apiVersion : apps/v1
kind: Deployment
metadata:
  name: jakondpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakondpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: jakondpipelinesjavascriptdocker 
    spec:
      containers:
        - name: jakondpipelinesjavascriptdocker 
          image: testacrram.azurecr.io/jakondpipelinesjavascriptdocker
          ports:
          - containerPort: 8080